# Generated by Django 3.2.3 on 2022-10-28 08:17

from django.db import migrations

from ..group_perms import create_groups


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_groups)]
