# Generated by Django 3.2.3 on 2022-10-05 19:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parcels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Uploads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("areah", models.FloatField(default=0, verbose_name="Area")),
                ("perm", models.FloatField(default=0, verbose_name="Perimeter")),
                ("plotno", models.BigIntegerField(unique=True, verbose_name="Plot NO")),
                (
                    "lrnumber",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="LRNumber"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        srid=4326, verbose_name="Geometry"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "uploads",
                "db_table": "uploads",
            },
        ),
        migrations.CreateModel(
            name="Parcels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("areah", models.FloatField(default=0, verbose_name="Area")),
                ("perm", models.FloatField(default=0, verbose_name="Perimeter")),
                ("plotno", models.BigIntegerField(unique=True, verbose_name="Plot NO")),
                (
                    "lrnumber",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="LRNumber"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, verbose_name="Geometry"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "parcels",
                "db_table": "parcels",
            },
        ),
    ]
